inicio:
    pattern: /
    defaults: { _controller: InicioBundle:Default:index }

admin:
    pattern: /admin
    defaults: { _controller: InicioBundle:Admin:index }
    
login_check:
    pattern: /login_check

logout:
    pattern: /logout

default_admin:
    resource: "@InicioBundle/Controller/AdminController.php"
    type:     annotation

autor:
    resource: "@InicioBundle/Controller/AutorController.php"
    type:     annotation
    
categoria:
    resource: "@InicioBundle/Controller/CategoriaController.php"
    type:     annotation
    
direccion:
    resource: "@InicioBundle/Controller/DireccionController.php"
    type:     annotation
    
editorial:
    resource: "@InicioBundle/Controller/EditorialController.php"
    type:     annotation
    
estado:
    resource: "@InicioBundle/Controller/EstadoController.php"
    type:     annotation
    
libro:
    resource: "@InicioBundle/Controller/LibroController.php"
    type:     annotation

pedido:
    resource: "@InicioBundle/Controller/PedidoController.php"
    type:     annotation

localidad:
    resource: "@InicioBundle/Controller/LocalidadController.php"
    type:     annotation
    
provincia:
    resource: "@InicioBundle/Controller/ProvinciaController.php"
    type:     annotation

mensaje:
    resource: "@InicioBundle/Controller/MensajeController.php"
    type:     annotation
    
user:
    pattern: /Usuarios
    defaults: { _controller: InicioBundle:Security:index } 
    
login:
    pattern: /login
    defaults: { _controller: InicioBundle:Security:login }
    

removeLibro:
    pattern: /removeLibro/{id}
    defaults: { _controller: InicioBundle:Libro:remove }

removeAutor:
    pattern: /removeAutor/{id}
    defaults: { _controller: InicioBundle:Autor:remove }
    
removeCategoria:
    pattern: /removeCategoria/{id}
    defaults: { _controller: InicioBundle:Categoria:remove }
    
removeEditorial:
    pattern: /removeEditorial/{id}
    defaults: { _controller: InicioBundle:Editorial:remove }
    
conformarCarrito:
    pattern: /conformarCarrito
    defaults: { _controller: InicioBundle:Pedido:conformarCarrito }
    
compraPasoUno:
    pattern: /compraPasoUno
    defaults: { _controller: InicioBundle:Pedido:compraPasoUno }
    
compraPasoDos:
    pattern: /compraPasoDos
    defaults: { _controller: InicioBundle:Pedido:compraPasoDos }
    
buscarLocalidades:
    pattern: /buscarLocalidades
    defaults: { _controller: InicioBundle:Pedido:buscarLocalidades }
    
buscarDatosTarjeta:
    pattern: /buscarDatosTarjeta
    defaults: { _controller: InicioBundle:Pedido:buscarDatosTarjeta }
    
buscarPedidos:
    pattern: /buscarPedidos
    defaults: { _controller: InicioBundle:Pedido:buscarPedidos }

contacto:
    pattern:  /contacto
    defaults: { _controller: InicioBundle:Default:contacto }
    
ayuda:
    pattern:  /ayuda
    defaults: { _controller: InicioBundle:Default:ayuda }
    
marcarMail:
    pattern:  /marcar/{id}
    defaults: { _controller: InicioBundle:Mensaje:marcar }
    
finalizarCompra:
    pattern:  /finPedido
    defaults: { _controller: InicioBundle:Pedido:finalizarCompra }
    
    