inicio:
    pattern: /
    defaults: { _controller: InicioBundle:Default:index }

admin:
    pattern: /admin
    defaults: { _controller: InicioBundle:Admin:index }
    
login_check:
    pattern: /login_check

logout:
    pattern: /logout

default_admin:
    resource: "@InicioBundle/Controller/AdminController.php"
    type:     annotation

autor:
    resource: "@InicioBundle/Controller/AutorController.php"
    type:     annotation
    
categoria:
    resource: "@InicioBundle/Controller/CategoriaController.php"
    type:     annotation
    
direccion:
    resource: "@InicioBundle/Controller/DireccionController.php"
    type:     annotation
    
editorial:
    resource: "@InicioBundle/Controller/EditorialController.php"
    type:     annotation
    
estado:
    resource: "@InicioBundle/Controller/EstadoController.php"
    type:     annotation
    
libro:
    resource: "@InicioBundle/Controller/LibroController.php"
    type:     annotation

pedido:
    resource: "@InicioBundle/Controller/PedidoController.php"
    type:     annotation

localidad:
    resource: "@InicioBundle/Controller/LocalidadController.php"
    type:     annotation
    
provincia:
    resource: "@InicioBundle/Controller/ProvinciaController.php"
    type:     annotation

mensaje:
    resource: "@InicioBundle/Controller/MensajeController.php"
    type:     annotation
    
user:
    pattern: admin/usuarios
    defaults: { _controller: InicioBundle:Security:index } 
    
login:
    pattern: /login
    defaults: { _controller: InicioBundle:Security:login }
    
changePassword:
    pattern: /changePassword
    defaults: { _controller: InicioBundle:ChangePassword:changePassword }
    
removeLibro:
    pattern: admin/libro/removeLibro/{id}
    defaults: { _controller: InicioBundle:Libro:remove }

removeAutor:
    pattern: admin/autor/removeAutor/{id}
    defaults: { _controller: InicioBundle:Autor:remove }
    
removeCategoria:
    pattern: admin/categoria/removeCategoria/{id}
    defaults: { _controller: InicioBundle:Categoria:remove }
    
removeEditorial:
    pattern: admin/editorial/removeEditorial/{id}
    defaults: { _controller: InicioBundle:Editorial:remove }
    
conformarCarrito:
    pattern: /conformarCarrito
    defaults: { _controller: InicioBundle:Pedido:conformarCarrito }
    
compraPasoUno:
    pattern: /compraPasoUno
    defaults: { _controller: InicioBundle:Pedido:compraPasoUno }
    
compraPasoDos:
    pattern: /compraPasoDos
    defaults: { _controller: InicioBundle:Pedido:compraPasoDos }
    
buscarLocalidades:
    pattern: /buscarLocalidades
    defaults: { _controller: InicioBundle:Pedido:buscarLocalidades }
    
buscarDatosTarjeta:
    pattern: /buscarDatosTarjeta
    defaults: { _controller: InicioBundle:Pedido:buscarDatosTarjeta }
    
buscarPedidos:
    pattern: /buscarPedidos
    defaults: { _controller: InicioBundle:Pedido:buscarPedidos }
    
setEstado:
    pattern: admin/setEstado
    defaults: { _controller: InicioBundle:Pedido:setEstado }
    
enviarMail:
    pattern: /enviarMail
    defaults: { _controller: InicioBundle:Default:GuardarMsj }
    
buscarCant:
    pattern: /buscarPedidosAdmin
    defaults: { _controller: InicioBundle:Admin:buscarCant }

contacto:
    pattern:  /contacto
    defaults: { _controller: InicioBundle:Default:contacto }
    
ayuda:
    pattern:  /ayuda
    defaults: { _controller: InicioBundle:Default:ayuda }
    
marcarMail:
    pattern:  /marcar/{id}
    defaults: { _controller: InicioBundle:Mensaje:marcar }
    
finalizarCompra:
    pattern:  /finPedido
    defaults: { _controller: InicioBundle:Pedido:finalizarCompra }
    
terminarCompra:
    pattern:  /terminarCompra/{id}
    defaults: { _controller: InicioBundle:Pedido:compraPasoDosTerminar }

ListarPedidos:
    pattern:  /ListarPedidos
    defaults: { _controller: InicioBundle:Default:listPedidos }
    
checkMail:
    pattern:  /CheckMail
    defaults: { _controller: InicioBundle:Default:checkMail }
    
checkEmailRecovery:
    pattern:  /CheckMailRecovery
    defaults: { _controller: InicioBundle:Default:checkEmailRecovery }
    
pedidos:
    pattern:  admin/listaDePedidos
    defaults: { _controller: InicioBundle:Admin:listPedidos }

verPedido:
    pattern:  /verPedido/{id}
    defaults: { _controller: InicioBundle:Default:verPedido }
    
verPedidoAdmin:
    pattern:  admin/verPedido/{id}
    defaults: { _controller: InicioBundle:Admin:verPedido }
    
filtroLibro:
    pattern:  admin/autor/libroFiltro
    defaults: { _controller: InicioBundle:Filtrado:filterLibro }
    
filtroAutor:
    pattern:  admin/autor/autorFiltro
    defaults: { _controller: InicioBundle:Filtrado:filterAutor }
    
filtroEditorial:
    pattern:  admin/editorial/editorialFiltro
    defaults: { _controller: InicioBundle:Filtrado:filterEditorial }
    
filtroCategoria:
    pattern:  admin/editorial/CategoriaFiltro
    defaults: { _controller: InicioBundle:Filtrado:filterCategoria }
    
filtroPrincipal:
    pattern:  /FiltroPrincipal
    defaults: { _controller: InicioBundle:Filtrado:filterMain }
    
perfil:
    pattern:  /miperfil
    defaults: { _controller: InicioBundle:Default:perfil }
    
usuarioBorrar:
    pattern:  /eliminarUsuario/{id}
    defaults: { _controller: InicioBundle:Default:borrarUsuario }
  
balance:
    pattern:  admin/balance
    defaults: { _controller: InicioBundle:Admin:balance }
    
cambiarMail:
    pattern:  /cambiarMail
    defaults: { _controller: InicioBundle:Default:cambiarEmail }
    
cambiarUsername:
    pattern:  /cambiarUsername
    defaults: { _controller: InicioBundle:Default:cambiarNombreUsuario }
